Feature addition: Cancel order
animus-coop/ecommerce-drive pull request #9
Opened 2023-03-17 15:36 UTC by Gianluca-w

User now can cancel its own order via a button in the cart section

2023-03-17 18:45 UTC, isa95Ar requested changes
Gian fijate si la api es accesible cuando estas logeado yo creeria que no por que tenemos un middleware pero fijate si esta andando bien dale por las dudas podes probar con el postman.

2023-03-17 18:45 UTC, isa95Ar commented on pages/cart.tsx
> +									disabled={cart.products.length < 0}
aqui yo creo que podriamos agregar la validacion de isEditingOrder si eso esta false la props disabled tendria que tener true viste igual creo que lo mejor seria no mostrar el boton si isEditingOrder da false

2023-03-17 19:00 UTC, Gianluca-w commented on pages/cart.tsx
> +									disabled={cart.products.length < 0}
Listo, Postman devuelve auth required

2023-03-29 17:22 UTC, isa95Ar approved these changes

2023-03-29 17:22 UTC, merged